import type { ContentSchema } from "./types";

/** Types de contenu du site « La Cave des P'tits Bonheurs ». */
export const lacaveSchema: ContentSchema = {
  key: "lacave",
  // Couleurs et polices du site (css/style.css du site : --c1, --c2, --c3).
  branding: {
    primary: "#3a5163",
    primaryHover: "#2f4553",
    primarySoft: "#e4eaee",
    accent: "#d06a30",
    background: "#f4f0e8",
    text: "#26343f",
    logo: "/clients/lacave/logo.png",
    fontTitle: "'Cormorant Garamond', Georgia, serif",
    fontsHref: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600&display=swap",
  },
  types: [
    {
      key: "produit",
      slug: "produits",
      labelSingular: "produit",
      labelPlural: "produits",
      icon: "🍷",
      titleField: "nom",
      subtitleField: "producteur",
      imageField: "photo",
      filterField: "categorie",
      badgeField: "nouveaute",
      fields: [
        { name: "nom", label: "Nom du produit", kind: "text", required: true, maxLength: 120,
          placeholder: "Ex. : Pommard" },
        { name: "producteur", label: "Domaine ou producteur", kind: "text", maxLength: 120,
          placeholder: "Ex. : Château de Pommard" },
        { name: "categorie", label: "Catégorie", kind: "select", required: true, default: "vins",
          options: [
            { value: "vins", label: "Vins" },
            { value: "bieres", label: "Bières" },
            { value: "spiritueux", label: "Spiritueux" },
            { value: "epicerie", label: "Épicerie fine" },
          ] },
        // ----- Critères propres à chaque catégorie (servent aussi de filtres) -----
        { name: "type", label: "Couleur", kind: "select", required: true, default: "rouge", filter: true,
          showIf: { field: "categorie", in: ["vins"] },
          help: "Sert aussi à choisir la couleur de la bouteille dessinée quand il n'y a pas de photo.",
          options: [
            { value: "rouge", label: "Rouge" },
            { value: "blanc", label: "Blanc" },
            { value: "rose", label: "Rosé" },
            { value: "effervescent", label: "Effervescent" },
            { value: "doux", label: "Doux & liquoreux" },
          ] },
        { name: "region", label: "Région", kind: "select", filter: true,
          showIf: { field: "categorie", in: ["vins"] },
          options: [
            { value: "languedoc", label: "Languedoc-Roussillon" },
            { value: "provence", label: "Provence" },
            { value: "rhone", label: "Vallée du Rhône" },
            { value: "sud-ouest", label: "Sud-Ouest" },
            { value: "bordeaux", label: "Bordeaux" },
            { value: "bourgogne", label: "Bourgogne" },
            { value: "beaujolais", label: "Beaujolais" },
            { value: "loire", label: "Val de Loire" },
            { value: "alsace", label: "Alsace" },
            { value: "champagne", label: "Champagne" },
            { value: "jura-savoie", label: "Jura & Savoie" },
            { value: "corse", label: "Corse" },
            { value: "monde", label: "Vins du monde" },
          ] },
        { name: "style", label: "Style de bière", kind: "select", filter: true,
          showIf: { field: "categorie", in: ["bieres"] },
          options: [
            { value: "blonde", label: "Blonde" },
            { value: "blanche", label: "Blanche" },
            { value: "ambree", label: "Ambrée" },
            { value: "brune", label: "Brune" },
            { value: "ipa", label: "IPA" },
            { value: "stout", label: "Stout & porter" },
            { value: "sans-alcool", label: "Sans alcool" },
            { value: "autre", label: "Autre" },
          ] },
        { name: "type_spiritueux", label: "Type de spiritueux", kind: "select", filter: true,
          showIf: { field: "categorie", in: ["spiritueux"] },
          options: [
            { value: "whisky", label: "Whisky" },
            { value: "rhum", label: "Rhum" },
            { value: "gin", label: "Gin" },
            { value: "cognac-armagnac", label: "Cognac & Armagnac" },
            { value: "vodka", label: "Vodka" },
            { value: "eau-de-vie", label: "Eaux-de-vie" },
            { value: "liqueur", label: "Liqueurs & crèmes" },
            { value: "aperitif", label: "Apéritifs" },
            { value: "autre", label: "Autre" },
          ] },
        { name: "rayon", label: "Rayon", kind: "select", filter: true,
          showIf: { field: "categorie", in: ["epicerie"] },
          options: [
            { value: "aperitif", label: "Apéritif salé" },
            { value: "terrines", label: "Terrines & rillettes" },
            { value: "huiles", label: "Huiles & vinaigres" },
            { value: "sucre", label: "Sucré & confiseries" },
            { value: "the-cafe", label: "Thés & cafés" },
            { value: "coffrets", label: "Coffrets cadeaux" },
            { value: "autre", label: "Autre" },
          ] },
        { name: "millesime", label: "Millésime", kind: "integer", min: 1900, max: 2100,
          showIf: { field: "categorie", in: ["vins", "spiritueux"] },
          help: "Année de récolte ou de distillation. Laisser vide si sans objet." },
        { name: "prix", label: "Prix (€)", kind: "price", required: true },
        { name: "description", label: "Description courte", kind: "textarea", maxLength: 600 },
        { name: "photo", label: "Photo", kind: "image",
          help: "Facultative. Sans photo, le site affiche une bouteille dessinée." },
        { name: "nouveaute", label: "Afficher dans les « Nouveautés » de l'accueil",
          kind: "boolean", default: false },
      ],
    },
    {
      key: "evenement",
      slug: "evenements",
      labelSingular: "événement",
      labelPlural: "événements",
      titleField: "titre",
      subtitleField: "lieu",
      imageField: "image",
      schedule: { startField: "debut", endField: "fin" },
      fields: [
        { name: "titre", label: "Titre", kind: "text", required: true, maxLength: 120,
          placeholder: "Ex. : Atelier dégustation vins de Bourgogne" },
        { name: "debut", label: "Début", kind: "datetime", required: true },
        { name: "fin", label: "Fin", kind: "datetime",
          help: "Facultative. Sans fin, l'événement disparaît du site 6 heures après son début." },
        { name: "lieu", label: "Lieu", kind: "text", maxLength: 160,
          placeholder: "À la cave" },
        { name: "description", label: "Description", kind: "textarea", maxLength: 2000 },
        { name: "infos", label: "Prix et infos pratiques", kind: "text", maxLength: 200,
          placeholder: "Ex. : 25 € par personne, sur réservation" },
        { name: "lien_inscription", label: "Lien d'inscription", kind: "url",
          help: "Facultatif. Adresse d'une page externe de réservation." },
        { name: "image", label: "Image", kind: "image" },
      ],
    },
  ],
};
